[package]
name = "b64"
version = "0.0.1"
authors = ["zydxhs <johnsmithcry@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"